# Generated by Django 3.2.7 on 2021-10-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto',
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ManyToManyField(to='perfil.Imagem'),
        ),
    ]
