# Generated by Django 3.2.7 on 2021-10-11 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagens', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('titulo', models.TextField()),
                ('descricao', models.TextField()),
                ('foto', models.ManyToManyField(to='chamado.Imagem')),
                ('realizado_por', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamado.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('status', models.TextField()),
                ('data_abertura', models.DateTimeField()),
                ('data_finalizado', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('atendentes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendente', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='chamado.categoria')),
                ('finalizado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalizador', to=settings.AUTH_USER_MODEL)),
                ('foto', models.ManyToManyField(to='chamado.Imagem')),
                ('procedimentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='chamado.procedimento')),
                ('solicitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='chamado.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamado.tipo')),
            ],
        ),
    ]
